services:
  orchestrator:
    build: ./orchestrator
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - knowledge_agent
      - mcp_tool_server

  knowledge_agent:
    build: ./knowledge_agent
    env_file:
      - ../.env
    ports:
      - "8001:8001"

  mcp_tool_server:
    build: ./mcp_tool_server
    env_file:
      - ../.env
    ports:
      - "8002:8002"
